export namespace CONSTANTS {
  export enum PROVIDERS {
    HASH_PROVIDER = 'HashProvider',
    JWT_PROVIDER = 'JwtProvider',
    JWT_SERVICE = 'JwtService',
    ICS_PROVIDER = 'IcsProvider',
    MAIL_SERVICE = 'MailService',
    USER_SERVICE = 'UserService',
    ROLE_SERVICE = 'RoleService',
    CAREER_SERVICE = 'CareerService',
    AUTH_SERVICE = 'AuthService',
    REASON_SERVICE = 'ReasonService',
    CAUSE_SERVICE = 'CauseService',
    MENU_SERVICE = 'MenuService',
    APPOINTMENT_SERVICE = 'AppointmentService',
    STATUS_SERVICE = 'StatusService',
    SCHEDULE_SERVICE = 'ScheduleService',
  }

  export enum USE_CASES {
    CREATE_USER_USE_CASE = 'CreateUserUseCase',
    GET_USER_DOCUMENTS_USE_CASE = 'GetDocumentsUseCase',
    UPDATE_USER_USE_CASE = 'UpdateUserUseCase',
    GET_USER_USE_CASE = 'GetUserUseCase',
    GET_PSYCHOLOGIST_USE_CASE = 'GetPsychologistUseCase',
    GET_ALL_USER_USE_CASE = 'GetAllUsersUseCase',
    GET_ALL_ROLES_USE_CASE = 'GetAllRolesUseCase',
    GET_ALL_CAREER_USE_CASE = 'GetAllCareerUseCase',
    GET_CAREER_USE_CASE = 'GetCareerUseCase',
    AUTH_USER_USE_CASE = 'AuthUserUseCase',
    GET_REASONS_USE_CASE = 'GetReasonsUseCase',
    CREATE_REASON_USE_CASE = 'CreateReasonUseCase',
    GET_REASON_USE_CASE = 'GetReasonUseCase',
    UPDATE_REASON_USE_CASE = 'UpdateReasonUseCase',
    CREATE_CAUSE_USE_CASE = 'CreateCauseUseCase',
    UPDATE_CAUSE_USE_CASE = 'UpdateCauseUseCase',
    GET_CAUSE_BY_REASON_USE_CASE = 'GetCauseByReasonUseCase',
    GET_MENU_USE_CASE = 'GetMenuUseCase',
    ADD_ITEM_MENU_USE_CASE = 'AddItemUseCase',
    UPDATE_MENU_USE_CASE = 'UpdateMenuUseCase',
    GET_MENU_BY_ID_USE_CASE = 'GetMenuByIDCaseUse',
    DELETE_MENU_USE_CASE = 'DeleteMenuUseCase',
    CREATE_APPOINTMENT_USE_CASE = 'CreateAppointmentUseCase',
    CURRENT_APPOINTMENT_USE_CASE = 'CurrentAppointmentUseCase',
    GET_HISTORY_APPOINTMENT_USE_CASE = 'GetHistoryAppointmentUseCase',
    UPDATE_APPOINTMENT_USE_CASE = 'UpdateStatusAppointmentUseCase',
    GET_ALL_APPOINTMENTS_USE_CASE = 'GetAllAppointmentsUSeCase',
    CREATE_SCHEDULE_USE_CASE = 'CreateScheduleUseCase',
    GET_SCHEDULE_USE_CASE = 'GetScheduleUseCase',
  }
}
